import type { Property } from './types'

export const properties: Property[] = [
  {
    id: '1',
    title: 'Victorian Terrace',
    location: 'Peckham, London',
    description: 'A three-bedroom Victorian terrace with original features. Structurally sound but in need of full interior renovation — damp works, rewire, new kitchen and bathrooms.',
    currentValuation: 320000,
    potentialValuation: 520000,
    renovationCost: 85000,
    bedrooms: 3,
    sqft: 1100,
    status: 'available',
    imageUrl: '/property/peckham.jpg',
    tags: ['Victorian', 'Terrace', 'South London'],
    completionMonths: 8,
  },
  {
    id: '2',
    title: 'Edwardian Semi-Detached',
    location: 'Levenshulme, Manchester',
    description: 'Spacious four-bedroom Edwardian semi in an up-and-coming suburb. Requires new roof, full kitchen extension, and updated electrics throughout.',
    currentValuation: 210000,
    potentialValuation: 370000,
    renovationCost: 65000,
    bedrooms: 4,
    sqft: 1450,
    status: 'available',
    imageUrl: '/property/manchester.jpg',
    tags: ['Edwardian', 'Semi-detached', 'Manchester'],
    completionMonths: 10,
  },
  {
    id: '3',
    title: 'Industrial Warehouse Conversion',
    location: 'Digbeth, Birmingham',
    description: 'Former light industrial unit with planning permission granted for 6 luxury apartments. Excellent transport links and strong rental demand in the area.',
    currentValuation: 480000,
    potentialValuation: 980000,
    renovationCost: 290000,
    bedrooms: 6,
    sqft: 4800,
    status: 'under_offer',
    imageUrl: '/property/digbeth.jpg',
    tags: ['Conversion', 'Commercial', 'Birmingham'],
    completionMonths: 18,
  },
  {
    id: '4',
    title: '1970s Detached Bungalow',
    location: 'Whitley Bay, Newcastle',
    description: 'Detached bungalow with large rear garden and potential to extend into the loft. Requires full cosmetic overhaul, new heating system and landscaping.',
    currentValuation: 195000,
    potentialValuation: 310000,
    renovationCost: 55000,
    bedrooms: 3,
    sqft: 950,
    status: 'available',
    imageUrl: '/property/newcastle.jpg',
    tags: ['Bungalow', 'Detached', 'North East'],
    completionMonths: 7,
  },
  {
    id: '5',
    title: 'Georgian Townhouse',
    location: 'Clifton, Bristol',
    description: 'Grade II listed Georgian townhouse over five floors. Strip-out complete. Requires careful period restoration with modern amenities throughout.',
    currentValuation: 650000,
    potentialValuation: 1150000,
    renovationCost: 240000,
    bedrooms: 5,
    sqft: 2900,
    status: 'available',
    imageUrl: '/property/bristol.jpg',
    tags: ['Georgian', 'Listed', 'Bristol'],
    completionMonths: 14,
  },
  {
    id: '6',
    title: 'Post-War Flat Block',
    location: 'Roath, Cardiff',
    description: 'A block of 4 flats from the 1950s. Planning granted for two additional units via mansard extension. Full refurb of all units required.',
    currentValuation: 390000,
    potentialValuation: 720000,
    renovationCost: 195000,
    bedrooms: 8,
    sqft: 3200,
    status: 'sold',
    imageUrl: '/property/cardiff.jpg',
    tags: ['Flats', 'Block', 'Cardiff'],
    completionMonths: 16,
  },
]
