export interface CouncilData {
  name: string
  region: 'london' | 'england' | 'scotland' | 'wales' | 'northern-ireland'
  licenceType: string
  feeRange: string
  processingTime: string
  applicationUrl: string
  notes: string
  consent: boolean
}

export const universalRequirements = [
  {
    id: 'food-reg',
    title: 'Food Business Registration',
    description: 'Register with your local council at least 28 days before you start trading. Free — done via gov.uk.',
    link: 'https://www.gov.uk/food-business-registration',
    linkText: 'Register on gov.uk',
    priority: 1,
  },
  {
    id: 'hygiene-cert',
    title: 'Level 2 Food Hygiene Certificate',
    description: 'Required for anyone handling food. Can be completed online in a few hours. Cost: £15–£40.',
    link: 'https://www.highspeedtraining.co.uk/food-hygiene/',
    linkText: 'Get certified online',
    priority: 2,
  },
  {
    id: 'public-liability',
    title: 'Public Liability Insurance',
    description: 'Minimum £5 million cover required. Most councils will not grant a licence without it. Cost: ~£150–£500/year.',
    link: 'https://www.simplybusiness.co.uk/street-food-insurance/',
    linkText: 'Compare insurance',
    priority: 3,
  },
  {
    id: 'haccp',
    title: 'Food Safety Management System (HACCP)',
    description: 'A written plan showing how you manage food safety. Use the free Safer Food Better Business pack from the FSA.',
    link: 'https://www.food.gov.uk/business-guidance/safer-food-better-business',
    linkText: 'Download free FSA pack',
    priority: 4,
  },
]

export const councilData: CouncilData[] = [
  // ── LONDON BOROUGHS ──────────────────────────────────────────
  {
    name: 'City of London',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£500–£1,200/year',
    processingTime: '6–8 weeks',
    applicationUrl: 'https://www.cityoflondon.gov.uk/services/licensing/street-trading',
    notes: 'Temporary licences available for City events. Consent zones apply in the Square Mile.',
    consent: false,
  },
  {
    name: 'Barking & Dagenham',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£300–£600/year',
    processingTime: '4–6 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Apply to the council licensing team. Limited designated pitches available.',
    consent: false,
  },
  {
    name: 'Barnet',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£350–£700/year',
    processingTime: '4–8 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Council designates specific street trading locations. Check available pitches before applying.',
    consent: false,
  },
  {
    name: 'Bexley',
    region: 'london',
    licenceType: 'Street Trading Consent',
    feeRange: '£250–£500/year',
    processingTime: '4–6 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Uses consent system. Fewer formal restrictions than full licence boroughs.',
    consent: true,
  },
  {
    name: 'Brent',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£400–£800/year',
    processingTime: '6–10 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'High demand borough. Apply well in advance. Wembley area has specific regulations.',
    consent: false,
  },
  {
    name: 'Bromley',
    region: 'london',
    licenceType: 'Street Trading Consent',
    feeRange: '£200–£450/year',
    processingTime: '3–6 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Consent borough. Bromley town centre has designated pitches. Market trading also available.',
    consent: true,
  },
  {
    name: 'Camden',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£600–£1,500/year',
    processingTime: '8–12 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'One of the most competitive boroughs. Camden Market area heavily regulated. Apply early.',
    consent: false,
  },
  {
    name: 'Croydon',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£350–£700/year',
    processingTime: '4–8 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Town centre pitches in high demand. Also check Croydon Market for pitch opportunities.',
    consent: false,
  },
  {
    name: 'Ealing',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£400–£800/year',
    processingTime: '6–8 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Multiple town centres (Ealing, Southall, Acton). Check which area you want to trade in.',
    consent: false,
  },
  {
    name: 'Enfield',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£300–£600/year',
    processingTime: '4–8 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Check designated street trading locations list before applying.',
    consent: false,
  },
  {
    name: 'Greenwich',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£500–£1,000/year',
    processingTime: '6–10 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Greenwich town centre and market area highly sought after. Tourist footfall strong.',
    consent: false,
  },
  {
    name: 'Hackney',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£600–£1,200/year',
    processingTime: '6–10 weeks',
    applicationUrl: 'https://hackney.gov.uk/markets-apply-to-trade/',
    notes: 'Strong street food scene. Broadway Market, Ridley Road, Well Street areas popular. Very competitive.',
    consent: false,
  },
  {
    name: 'Hammersmith & Fulham',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£400–£900/year',
    processingTime: '6–8 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Hammersmith and Kings Road/Fulham areas regulated separately. Check available locations.',
    consent: false,
  },
  {
    name: 'Haringey',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£350–£700/year',
    processingTime: '4–8 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Wood Green, Tottenham Hale and Seven Sisters areas. Growing food scene.',
    consent: false,
  },
  {
    name: 'Harrow',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£300–£600/year',
    processingTime: '4–6 weeks',
    applicationUrl: 'https://www.harrow.gov.uk/licences/street-trading/3',
    notes: 'Harrow town centre designated pitches. Also check Wealdstone area.',
    consent: false,
  },
  {
    name: 'Havering',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£250–£550/year',
    processingTime: '4–6 weeks',
    applicationUrl: 'https://www.havering.gov.uk/info/20003/licences_and_permits/127/street_trading_licence',
    notes: 'Romford and Hornchurch town centres. Romford market area well established.',
    consent: false,
  },
  {
    name: 'Hillingdon',
    region: 'london',
    licenceType: 'Street Trading Consent',
    feeRange: '£250–£500/year',
    processingTime: '4–6 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Consent borough. Uxbridge and Hayes town centres. Heathrow proximity brings opportunities.',
    consent: true,
  },
  {
    name: 'Hounslow',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£350–£700/year',
    processingTime: '4–8 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Hounslow, Chiswick and Brentford areas. Busy high streets.',
    consent: false,
  },
  {
    name: 'Islington',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£600–£1,400/year',
    processingTime: '8–12 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Angel, Upper Street, Chapel Market areas. Very high demand. Apply well in advance.',
    consent: false,
  },
  {
    name: 'Kensington & Chelsea',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£800–£2,000/year',
    processingTime: '8–12 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Most expensive borough. Portobello Road, Kings Road, Notting Hill. Very limited pitches.',
    consent: false,
  },
  {
    name: 'Kingston upon Thames',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£400–£800/year',
    processingTime: '6–8 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Kingston town centre and Ancient Market. Strong footfall especially weekends.',
    consent: false,
  },
  {
    name: 'Lambeth',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£500–£1,000/year',
    processingTime: '6–10 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Brixton, Clapham, Streatham areas. Brixton Market area particularly popular.',
    consent: false,
  },
  {
    name: 'Lewisham',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£350–£700/year',
    processingTime: '4–8 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Lewisham, Catford and Deptford areas. Growing street food scene.',
    consent: false,
  },
  {
    name: 'Merton',
    region: 'london',
    licenceType: 'Street Trading Consent',
    feeRange: '£250–£500/year',
    processingTime: '4–6 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Consent borough. Wimbledon and Mitcham areas. Wimbledon town centre has good footfall.',
    consent: true,
  },
  {
    name: 'Newham',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£400–£800/year',
    processingTime: '6–8 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Stratford, West Ham, Green Street areas. Westfield proximity good for footfall.',
    consent: false,
  },
  {
    name: 'Redbridge',
    region: 'london',
    licenceType: 'Street Trading Consent',
    feeRange: '£250–£500/year',
    processingTime: '3–6 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Consent borough. Ilford and Woodford areas. Ilford town centre high footfall.',
    consent: true,
  },
  {
    name: 'Richmond upon Thames',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£500–£1,000/year',
    processingTime: '6–8 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Richmond, Twickenham and Kew areas. Affluent catchment area.',
    consent: false,
  },
  {
    name: 'Southwark',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£600–£1,200/year',
    processingTime: '8–12 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Borough Market area, Peckham, Bermondsey. Borough Market is separate — contact them directly.',
    consent: false,
  },
  {
    name: 'Sutton',
    region: 'london',
    licenceType: 'Street Trading Consent',
    feeRange: '£200–£450/year',
    processingTime: '3–6 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Consent borough. Sutton and Cheam town centres. Lower competition than inner London.',
    consent: true,
  },
  {
    name: 'Tower Hamlets',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£600–£1,300/year',
    processingTime: '8–12 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Brick Lane, Whitechapel, Canary Wharf, Shoreditch areas. Extremely competitive. Apply early.',
    consent: false,
  },
  {
    name: 'Waltham Forest',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£350–£700/year',
    processingTime: '4–8 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Walthamstow, Leyton, Leytonstone. Walthamstow Market (longest outdoor market in Europe) nearby.',
    consent: false,
  },
  {
    name: 'Wandsworth',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£400–£800/year',
    processingTime: '6–8 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Clapham Junction, Tooting, Battersea areas. Tooting Market popular for street food.',
    consent: false,
  },
  {
    name: 'Westminster',
    region: 'london',
    licenceType: 'Street Trading Licence',
    feeRange: '£800–£2,000/year',
    processingTime: '8–12 weeks',
    applicationUrl: 'https://www.westminster.gov.uk/licences-and-permits/street-trading',
    notes: 'Most regulated borough. Oxford Street, Covent Garden, Victoria areas. Very limited licences. Long waiting lists.',
    consent: false,
  },

  // ── ENGLAND — MAJOR CITIES ───────────────────────────────────
  {
    name: 'Birmingham',
    region: 'england',
    licenceType: 'Street Trading Licence',
    feeRange: '£400–£900/year',
    processingTime: '6–10 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Bullring, Digbeth, Broad Street areas. Strong and growing street food scene.',
    consent: false,
  },
  {
    name: 'Manchester',
    region: 'england',
    licenceType: 'Street Trading Licence',
    feeRange: '£400–£900/year',
    processingTime: '6–10 weeks',
    applicationUrl: 'https://www.manchester.gov.uk/info/200057/licensing_and_permits/4871/street_trading_licence',
    notes: 'Northern Quarter, Piccadilly, Spinningfields areas. Vibrant street food culture.',
    consent: false,
  },
  {
    name: 'Leeds',
    region: 'england',
    licenceType: 'Street Trading Consent',
    feeRange: '£300–£700/year',
    processingTime: '4–8 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'City centre, Kirkgate Market area. Consent system. Strong weekend footfall.',
    consent: true,
  },
  {
    name: 'Bristol',
    region: 'england',
    licenceType: 'Street Trading Consent',
    feeRange: '£300–£600/year',
    processingTime: '4–8 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Harbourside, Stokes Croft, Clifton areas. Excellent street food scene. St Nicholas Market popular.',
    consent: true,
  },
  {
    name: 'Liverpool',
    region: 'england',
    licenceType: 'Street Trading Licence',
    feeRange: '£350–£750/year',
    processingTime: '6–8 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'City centre, Baltic Triangle, Albert Dock areas. Growing food and drink scene.',
    consent: false,
  },
  {
    name: 'Sheffield',
    region: 'england',
    licenceType: 'Street Trading Consent',
    feeRange: '£250–£550/year',
    processingTime: '4–6 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'City centre, Kelham Island area. Relatively affordable compared to southern cities.',
    consent: true,
  },
  {
    name: 'Newcastle',
    region: 'england',
    licenceType: 'Street Trading Licence',
    feeRange: '£300–£650/year',
    processingTime: '4–8 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Grainger Market area, Quayside. Good student and night-time economy footfall.',
    consent: false,
  },
  {
    name: 'Nottingham',
    region: 'england',
    licenceType: 'Street Trading Consent',
    feeRange: '£250–£550/year',
    processingTime: '4–6 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Old Market Square area popular. Consent system. Strong university market.',
    consent: true,
  },
  {
    name: 'Brighton & Hove',
    region: 'england',
    licenceType: 'Street Trading Licence',
    feeRange: '£400–£900/year',
    processingTime: '6–10 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Seafront, The Lanes, North Laine areas. Strong tourist footfall especially summer.',
    consent: false,
  },
  {
    name: 'Leicester',
    region: 'england',
    licenceType: 'Street Trading Licence',
    feeRange: '£300–£650/year',
    processingTime: '4–8 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'City centre, Golden Mile area. Diverse food culture. Good footfall.',
    consent: false,
  },
  {
    name: 'Coventry',
    region: 'england',
    licenceType: 'Street Trading Consent',
    feeRange: '£250–£500/year',
    processingTime: '4–6 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'City centre market area. Consent system. Good student population.',
    consent: true,
  },
  {
    name: 'Southampton',
    region: 'england',
    licenceType: 'Street Trading Licence',
    feeRange: '£300–£650/year',
    processingTime: '4–8 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'City centre, waterfront areas. Port city with diverse customer base.',
    consent: false,
  },
  {
    name: 'Portsmouth',
    region: 'england',
    licenceType: 'Street Trading Licence',
    feeRange: '£250–£550/year',
    processingTime: '4–6 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Gunwharf Quays, Old Portsmouth areas. Seaside/naval city with good tourist footfall.',
    consent: false,
  },
  {
    name: 'Plymouth',
    region: 'england',
    licenceType: 'Street Trading Licence',
    feeRange: '£250–£550/year',
    processingTime: '4–6 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'City centre, Barbican area. Waterfront popular in summer months.',
    consent: false,
  },
  {
    name: 'Derby',
    region: 'england',
    licenceType: 'Street Trading Consent',
    feeRange: '£200–£450/year',
    processingTime: '3–6 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'City centre, Eagle Market area. Consent system. Lower cost than larger cities.',
    consent: true,
  },
  {
    name: 'Stoke-on-Trent',
    region: 'england',
    licenceType: 'Street Trading Consent',
    feeRange: '£200–£400/year',
    processingTime: '3–6 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Multiple town centres (Hanley, Burslem etc). One of the most affordable cities.',
    consent: true,
  },
  {
    name: 'Reading',
    region: 'england',
    licenceType: 'Street Trading Licence',
    feeRange: '£350–£700/year',
    processingTime: '4–8 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Town centre, Oracle area. Good commuter footfall. Close to London.',
    consent: false,
  },
  {
    name: 'Wolverhampton',
    region: 'england',
    licenceType: 'Street Trading Licence',
    feeRange: '£300–£600/year',
    processingTime: '4–8 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'City centre market area. Good footfall especially market days.',
    consent: false,
  },
  {
    name: 'Bradford',
    region: 'england',
    licenceType: 'Street Trading Consent',
    feeRange: '£250–£500/year',
    processingTime: '4–6 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'City centre, Kirkgate Market area. UK City of Culture 2025 — increased footfall expected.',
    consent: true,
  },
  {
    name: 'Exeter',
    region: 'england',
    licenceType: 'Street Trading Consent',
    feeRange: '£250–£550/year',
    processingTime: '4–6 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'City centre, Cathedral area. Strong student and tourist footfall. Less competitive than London.',
    consent: true,
  },

  // ── SCOTLAND ────────────────────────────────────────────────
  {
    name: 'Glasgow',
    region: 'scotland',
    licenceType: 'Pedlar Certificate + Local Permission',
    feeRange: '£100–£400/year',
    processingTime: '3–6 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Scotland uses different licensing system. Need Pedlar Certificate from Police Scotland + council permission. City centre and West End popular.',
    consent: false,
  },
  {
    name: 'Edinburgh',
    region: 'scotland',
    licenceType: 'Street Trading Licence (Scotland)',
    feeRange: '£200–£600/year',
    processingTime: '4–8 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Edinburgh Licensing Board regulates. Royal Mile, Grassmarket popular. Fringe Festival period especially lucrative.',
    consent: false,
  },

  // ── WALES ────────────────────────────────────────────────────
  {
    name: 'Cardiff',
    region: 'wales',
    licenceType: 'Street Trading Consent',
    feeRange: '£250–£600/year',
    processingTime: '4–8 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Wales uses consent system. Cardiff city centre, Cardiff Bay areas. Good rugby match day footfall.',
    consent: true,
  },

  // ── NORTHERN IRELAND ─────────────────────────────────────────
  {
    name: 'Belfast',
    region: 'northern-ireland',
    licenceType: 'Street Trading Licence (NI)',
    feeRange: '£200–£500/year',
    processingTime: '4–8 weeks',
    applicationUrl: 'https://www.gov.uk/street-trading-licence',
    notes: 'Northern Ireland has its own licensing framework under the Street Trading Act (NI) 2001. Cathedral Quarter, Victoria Square areas popular.',
    consent: false,
  },
]

export const getCouncilByName = (name: string): CouncilData | undefined => {
  return councilData.find(c => c.name.toLowerCase() === name.toLowerCase())
}

export const getLondonBoroughs = (): CouncilData[] => {
  return councilData.filter(c => c.region === 'london')
}

export const getMajorCities = (): CouncilData[] => {
  return councilData.filter(c => c.region !== 'london')
}
