export type Kitchen = {
  id: string
  name: string
  city: string
  area: string
  postcode: string
  type: ('shared' | 'dark' | 'ghost' | 'private' | 'incubator')[]
  pricePerHour: number
  pricePerMonth: number | null
  minHours: number
  maxCapacity: number // team size
  equipment: string[]
  certifications: string[]
  operatingHours: string
  availableShifts: ('morning' | 'afternoon' | 'evening' | 'overnight' | '24hr')[]
  storage: ('dry' | 'cold' | 'frozen')[]
  deliveryPlatforms: ('Deliveroo' | 'UberEats' | 'JustEat' | 'Own fleet')[]
  foodTypes: string[]
  website: string
  phone: string
  email: string
  description: string
  features: string[]
  rating: number
  reviewCount: number
  verified: boolean
}

export const kitchens: Kitchen[] = [
  {
    id: 'k001',
    name: 'Karma Kitchen Bermondsey',
    city: 'London',
    area: 'Bermondsey',
    postcode: 'SE1',
    type: ['dark', 'ghost'],
    pricePerHour: 0,
    pricePerMonth: 1500,
    minHours: 0,
    maxCapacity: 8,
    equipment: ['commercial oven', 'industrial fryer', 'griddle', 'cold room', 'blast chiller', 'pizza oven'],
    certifications: ['5-star hygiene', 'Gas Safe', 'Fire Safety'],
    operatingHours: '24/7',
    availableShifts: ['morning', 'afternoon', 'evening', 'overnight', '24hr'],
    storage: ['dry', 'cold', 'frozen'],
    deliveryPlatforms: ['Deliveroo', 'UberEats', 'JustEat'],
    foodTypes: ['hot meals', 'pizza', 'burgers', 'Asian', 'Mediterranean'],
    website: 'karma.kitchen',
    phone: '020 7123 4567',
    email: 'bermondsey@karma.kitchen',
    description: 'Professional ghost kitchen space in the heart of Bermondsey. Purpose-built for delivery brands with direct platform integrations.',
    features: ['24/7 access', 'delivery platform integration', 'CCTV', 'loading bay', 'staff lockers'],
    rating: 4.8,
    reviewCount: 94,
    verified: true,
  },
  {
    id: 'k002',
    name: 'Karma Kitchen Waterloo',
    city: 'London',
    area: 'Waterloo',
    postcode: 'SE1',
    type: ['dark', 'ghost'],
    pricePerHour: 0,
    pricePerMonth: 1800,
    minHours: 0,
    maxCapacity: 10,
    equipment: ['commercial oven', 'industrial fryer', 'wok burners', 'cold room', 'blast chiller'],
    certifications: ['5-star hygiene', 'Gas Safe'],
    operatingHours: '24/7',
    availableShifts: ['morning', 'afternoon', 'evening', 'overnight', '24hr'],
    storage: ['dry', 'cold', 'frozen'],
    deliveryPlatforms: ['Deliveroo', 'UberEats', 'JustEat'],
    foodTypes: ['hot meals', 'Asian', 'street food', 'healthy'],
    website: 'karma.kitchen',
    phone: '020 7123 4568',
    email: 'waterloo@karma.kitchen',
    description: 'High-footfall location near Waterloo Station. Ideal for brands targeting central London delivery demand.',
    features: ['24/7 access', 'high delivery demand area', 'multiple units available'],
    rating: 4.7,
    reviewCount: 71,
    verified: true,
  },
  {
    id: 'k003',
    name: 'Mission Kitchen White City',
    city: 'London',
    area: 'White City',
    postcode: 'W12',
    type: ['shared', 'incubator'],
    pricePerHour: 18,
    pricePerMonth: 800,
    minHours: 4,
    maxCapacity: 6,
    equipment: ['commercial oven', 'griddle', 'cold room', 'mixer', 'proofing oven', 'cold prep counter'],
    certifications: ['5-star hygiene', 'Gas Safe', 'Allergen compliant'],
    operatingHours: '06:00–22:00',
    availableShifts: ['morning', 'afternoon', 'evening'],
    storage: ['dry', 'cold', 'frozen'],
    deliveryPlatforms: ['Deliveroo', 'UberEats', 'Own fleet'],
    foodTypes: ['bakery', 'pastry', 'healthy', 'meal prep', 'catering'],
    website: 'missionkitchen.co.uk',
    phone: '020 8743 1234',
    email: 'hello@missionkitchen.co.uk',
    description: 'Food business incubator space with mentoring support. Perfect for early-stage food brands looking to scale up from home to commercial production.',
    features: ['business mentoring', 'brand development support', 'packaging storage', 'shared equipment', 'food tech community'],
    rating: 4.9,
    reviewCount: 128,
    verified: true,
  },
  {
    id: 'k004',
    name: 'Docklands Kitchen Hub',
    city: 'London',
    area: 'Canary Wharf',
    postcode: 'E14',
    type: ['shared', 'private'],
    pricePerHour: 22,
    pricePerMonth: 1200,
    minHours: 3,
    maxCapacity: 12,
    equipment: ['commercial oven x4', 'industrial fryer', 'griddle', 'cold room', 'blast chiller', 'dishwasher', 'prep counter'],
    certifications: ['5-star hygiene', 'Gas Safe', 'Fire Safety', 'ISO certified'],
    operatingHours: '05:00–23:00',
    availableShifts: ['morning', 'afternoon', 'evening'],
    storage: ['dry', 'cold', 'frozen'],
    deliveryPlatforms: ['Deliveroo', 'UberEats', 'JustEat', 'Own fleet'],
    foodTypes: ['corporate catering', 'hot meals', 'healthy', 'Asian', 'Mediterranean', 'events'],
    website: 'docklandskitchenhub.co.uk',
    phone: '020 7987 6543',
    email: 'info@docklandskitchenhub.co.uk',
    description: 'Modern commercial kitchen hub in Canary Wharf. Popular with corporate caterers and event catering companies serving the financial district.',
    features: ['corporate events focus', 'loading dock', 'cold storage vault', 'admin office', 'staff changing rooms'],
    rating: 4.6,
    reviewCount: 57,
    verified: true,
  },
  {
    id: 'k005',
    name: 'East End Food Hub',
    city: 'London',
    area: 'Hackney',
    postcode: 'E8',
    type: ['shared', 'incubator'],
    pricePerHour: 14,
    pricePerMonth: 650,
    minHours: 2,
    maxCapacity: 4,
    equipment: ['commercial oven', 'hob', 'cold room', 'mixer', 'prep tables'],
    certifications: ['5-star hygiene', 'Gas Safe'],
    operatingHours: '07:00–21:00',
    availableShifts: ['morning', 'afternoon', 'evening'],
    storage: ['dry', 'cold'],
    deliveryPlatforms: ['Deliveroo', 'UberEats', 'Own fleet'],
    foodTypes: ['street food', 'bakery', 'healthy', 'vegan', 'meal prep'],
    website: 'eastendFoodhub.co.uk',
    phone: '020 8123 9876',
    email: 'kitchen@eastendFoodhub.co.uk',
    description: 'Affordable shared kitchen in Hackney. Popular with street food startups, vegan brands and independent caterers. Strong creative food community.',
    features: ['affordable rates', 'flexible booking', 'community events', 'market stall connections'],
    rating: 4.5,
    reviewCount: 203,
    verified: true,
  },
  {
    id: 'k006',
    name: 'Notting Hill Kitchen Studios',
    city: 'London',
    area: 'Notting Hill',
    postcode: 'W11',
    type: ['private', 'shared'],
    pricePerHour: 35,
    pricePerMonth: 2200,
    minHours: 4,
    maxCapacity: 8,
    equipment: ['Rational combi oven', 'induction hobs', 'cold room', 'blast chiller', 'sous vide', 'Pacojet', 'vacuum sealer'],
    certifications: ['5-star hygiene', 'Gas Safe', 'Allergen compliant', 'Organic certified'],
    operatingHours: '06:00–22:00',
    availableShifts: ['morning', 'afternoon', 'evening'],
    storage: ['dry', 'cold', 'frozen'],
    deliveryPlatforms: ['Own fleet', 'Deliveroo'],
    foodTypes: ['fine dining', 'catering', 'healthy', 'organic', 'allergen-free', 'meal prep'],
    website: 'nottinghillkitchenstudios.co.uk',
    phone: '020 7229 8765',
    email: 'bookings@nottinghillkitchenstudios.co.uk',
    description: 'Premium kitchen studios in West London. Equipped to professional chef standard. Ideal for high-end caterers, private dining companies and food stylists.',
    features: ['premium equipment', 'food photography lighting', 'prop storage', 'private dining room', 'wine fridge'],
    rating: 4.9,
    reviewCount: 44,
    verified: true,
  },
  {
    id: 'k007',
    name: 'Manchester Food Works',
    city: 'Manchester',
    area: 'Ancoats',
    postcode: 'M4',
    type: ['shared', 'dark'],
    pricePerHour: 12,
    pricePerMonth: 700,
    minHours: 2,
    maxCapacity: 8,
    equipment: ['commercial oven', 'industrial fryer', 'griddle', 'cold room', 'prep tables', 'dishwasher'],
    certifications: ['5-star hygiene', 'Gas Safe'],
    operatingHours: '06:00–23:00',
    availableShifts: ['morning', 'afternoon', 'evening', 'overnight'],
    storage: ['dry', 'cold', 'frozen'],
    deliveryPlatforms: ['Deliveroo', 'UberEats', 'JustEat'],
    foodTypes: ['hot meals', 'street food', 'Asian', 'pizza', 'burgers', 'healthy'],
    website: 'manchesterfoodworks.co.uk',
    phone: '0161 234 5678',
    email: 'info@manchesterfoodworks.co.uk',
    description: 'Manchester\'s leading shared kitchen facility in the heart of Ancoats. Strong delivery infrastructure with all major platform integration.',
    features: ['late night access', 'delivery integration', 'CCTV', 'parking', 'loading area'],
    rating: 4.7,
    reviewCount: 167,
    verified: true,
  },
  {
    id: 'k008',
    name: 'Northern Quarter Kitchen Co.',
    city: 'Manchester',
    area: 'Northern Quarter',
    postcode: 'M1',
    type: ['shared', 'incubator'],
    pricePerHour: 10,
    pricePerMonth: 550,
    minHours: 2,
    maxCapacity: 5,
    equipment: ['commercial oven', 'hob', 'cold room', 'mixer', 'prep counter'],
    certifications: ['5-star hygiene', 'Gas Safe'],
    operatingHours: '07:00–20:00',
    availableShifts: ['morning', 'afternoon', 'evening'],
    storage: ['dry', 'cold'],
    deliveryPlatforms: ['UberEats', 'JustEat', 'Own fleet'],
    foodTypes: ['bakery', 'vegan', 'street food', 'healthy', 'meal prep'],
    website: 'nqkitchen.co.uk',
    phone: '0161 345 6789',
    email: 'hello@nqkitchen.co.uk',
    description: 'Affordable, community-focused kitchen in Manchester\'s creative Northern Quarter. Popular with food startups and small-batch producers.',
    features: ['flexible hourly booking', 'food startup community', 'cold storage lockers', 'event days'],
    rating: 4.6,
    reviewCount: 89,
    verified: true,
  },
  {
    id: 'k009',
    name: 'Leeds Central Kitchen',
    city: 'Leeds',
    area: 'City Centre',
    postcode: 'LS1',
    type: ['shared', 'dark'],
    pricePerHour: 11,
    pricePerMonth: 600,
    minHours: 3,
    maxCapacity: 10,
    equipment: ['commercial oven x3', 'industrial fryer', 'griddle', 'cold room', 'blast chiller', 'dishwasher'],
    certifications: ['5-star hygiene', 'Gas Safe', 'Fire Safety'],
    operatingHours: '24/7',
    availableShifts: ['morning', 'afternoon', 'evening', 'overnight', '24hr'],
    storage: ['dry', 'cold', 'frozen'],
    deliveryPlatforms: ['Deliveroo', 'UberEats', 'JustEat'],
    foodTypes: ['hot meals', 'pizza', 'burgers', 'Asian', 'street food'],
    website: 'leedscentralkitchen.co.uk',
    phone: '0113 234 5678',
    email: 'bookings@leedscentralkitchen.co.uk',
    description: 'Purpose-built ghost kitchen facility in Leeds city centre. 24/7 operation with full delivery platform integration. Growing rapidly with the Leeds food delivery market.',
    features: ['24/7 access', 'delivery integration', 'multiple units', 'CCTV', 'on-site support'],
    rating: 4.5,
    reviewCount: 112,
    verified: true,
  },
  {
    id: 'k010',
    name: 'Birmingham Food Factory',
    city: 'Birmingham',
    area: 'Digbeth',
    postcode: 'B5',
    type: ['shared', 'dark', 'ghost'],
    pricePerHour: 13,
    pricePerMonth: 750,
    minHours: 2,
    maxCapacity: 12,
    equipment: ['commercial oven x4', 'industrial fryer x2', 'griddle', 'tandoor', 'cold room x2', 'blast chiller', 'dishwasher'],
    certifications: ['5-star hygiene', 'Gas Safe', 'Halal certified'],
    operatingHours: '05:00–02:00',
    availableShifts: ['morning', 'afternoon', 'evening', 'overnight'],
    storage: ['dry', 'cold', 'frozen'],
    deliveryPlatforms: ['Deliveroo', 'UberEats', 'JustEat'],
    foodTypes: ['Asian', 'South Asian', 'hot meals', 'street food', 'halal', 'Mediterranean'],
    website: 'birminghamfoodfactory.co.uk',
    phone: '0121 456 7890',
    email: 'info@birminghamfoodfactory.co.uk',
    description: 'Largest commercial kitchen facility in Birmingham. Halal certified, tandoor equipped and with strong delivery platform presence across the Midlands.',
    features: ['halal certified', 'tandoor oven', 'late night access', 'loading bay', 'large cold storage'],
    rating: 4.7,
    reviewCount: 198,
    verified: true,
  },
  {
    id: 'k011',
    name: 'Bristol Kitchen Collective',
    city: 'Bristol',
    area: 'Stokes Croft',
    postcode: 'BS1',
    type: ['shared', 'incubator'],
    pricePerHour: 12,
    pricePerMonth: 580,
    minHours: 2,
    maxCapacity: 6,
    equipment: ['commercial oven', 'hob', 'cold room', 'mixer', 'juicer', 'dehydrator', 'prep tables'],
    certifications: ['5-star hygiene', 'Gas Safe', 'Organic certified', 'Vegan Society approved'],
    operatingHours: '07:00–21:00',
    availableShifts: ['morning', 'afternoon', 'evening'],
    storage: ['dry', 'cold'],
    deliveryPlatforms: ['Own fleet', 'UberEats'],
    foodTypes: ['vegan', 'organic', 'raw food', 'healthy', 'bakery', 'juices'],
    website: 'bristolkitchencollective.co.uk',
    phone: '0117 234 5678',
    email: 'hello@bristolkitchencollective.co.uk',
    description: 'Bristol\'s home for ethical and sustainable food businesses. Vegan Society approved, organic certified, and committed to zero-waste production.',
    features: ['zero waste policy', 'composting', 'renewable energy', 'community market access', 'branding support'],
    rating: 4.8,
    reviewCount: 76,
    verified: true,
  },
  {
    id: 'k012',
    name: 'Edinburgh Food Studio',
    city: 'Edinburgh',
    area: 'Leith',
    postcode: 'EH6',
    type: ['shared', 'private'],
    pricePerHour: 16,
    pricePerMonth: 900,
    minHours: 3,
    maxCapacity: 8,
    equipment: ['commercial oven', 'hob', 'cold room', 'blast chiller', 'vacuum sealer', 'sous vide', 'mixer'],
    certifications: ['5-star hygiene', 'Gas Safe', 'Food Standards Scotland approved'],
    operatingHours: '06:00–22:00',
    availableShifts: ['morning', 'afternoon', 'evening'],
    storage: ['dry', 'cold', 'frozen'],
    deliveryPlatforms: ['Deliveroo', 'UberEats', 'Own fleet'],
    foodTypes: ['Scottish cuisine', 'fine dining', 'catering', 'meal prep', 'bakery'],
    website: 'edinburghfoodstudio.co.uk',
    phone: '0131 234 5678',
    email: 'bookings@edinburghfoodstudio.co.uk',
    description: 'Premium kitchen studio in Leith, Edinburgh. Ideal for catering companies, supper clubs, and food producers looking to scale.',
    features: ['private hire available', 'product photography space', 'event space', 'rooftop herb garden'],
    rating: 4.8,
    reviewCount: 52,
    verified: true,
  },
  {
    id: 'k013',
    name: 'Shoreditch Ghost Kitchens',
    city: 'London',
    area: 'Shoreditch',
    postcode: 'EC2A',
    type: ['ghost', 'dark'],
    pricePerHour: 0,
    pricePerMonth: 2000,
    minHours: 0,
    maxCapacity: 6,
    equipment: ['commercial oven', 'industrial fryer', 'wok burners', 'cold room', 'blast chiller'],
    certifications: ['5-star hygiene', 'Gas Safe'],
    operatingHours: '24/7',
    availableShifts: ['morning', 'afternoon', 'evening', 'overnight', '24hr'],
    storage: ['dry', 'cold', 'frozen'],
    deliveryPlatforms: ['Deliveroo', 'UberEats', 'JustEat'],
    foodTypes: ['Asian', 'fusion', 'hot meals', 'burgers', 'pizza'],
    website: 'shoreditchghostkitchens.co.uk',
    phone: '020 7739 1234',
    email: 'ops@shoreditchghostkitchens.co.uk',
    description: 'Premium ghost kitchen space in Shoreditch — one of London\'s highest delivery demand zones. Monthly licence, fully equipped, 24/7.',
    features: ['prime delivery location', '24/7 access', 'dedicated unit', 'no shared equipment', 'high delivery volume zone'],
    rating: 4.6,
    reviewCount: 38,
    verified: true,
  },
  {
    id: 'k014',
    name: 'Glasgow Kitchen Hub',
    city: 'Glasgow',
    area: 'West End',
    postcode: 'G11',
    type: ['shared', 'dark'],
    pricePerHour: 10,
    pricePerMonth: 500,
    minHours: 2,
    maxCapacity: 8,
    equipment: ['commercial oven x2', 'fryer', 'griddle', 'cold room', 'prep tables', 'dishwasher'],
    certifications: ['5-star hygiene', 'Gas Safe'],
    operatingHours: '06:00–23:00',
    availableShifts: ['morning', 'afternoon', 'evening', 'overnight'],
    storage: ['dry', 'cold', 'frozen'],
    deliveryPlatforms: ['UberEats', 'JustEat', 'Own fleet'],
    foodTypes: ['hot meals', 'street food', 'Asian', 'healthy', 'catering'],
    website: 'glasgowkitchenhub.co.uk',
    phone: '0141 334 5678',
    email: 'info@glasgowkitchenhub.co.uk',
    description: 'Glasgow\'s most affordable shared kitchen facility. Growing food delivery market with increasing demand across the West End and city centre.',
    features: ['most affordable rates in Glasgow', 'late access', 'flexible contracts', 'storage lockers'],
    rating: 4.4,
    reviewCount: 61,
    verified: true,
  },
  {
    id: 'k015',
    name: 'Liverpool Street Food Lab',
    city: 'Liverpool',
    area: 'Baltic Triangle',
    postcode: 'L1',
    type: ['shared', 'incubator'],
    pricePerHour: 11,
    pricePerMonth: 580,
    minHours: 2,
    maxCapacity: 6,
    equipment: ['commercial oven', 'fryer', 'griddle', 'cold room', 'mixer', 'prep tables'],
    certifications: ['5-star hygiene', 'Gas Safe'],
    operatingHours: '07:00–22:00',
    availableShifts: ['morning', 'afternoon', 'evening'],
    storage: ['dry', 'cold', 'frozen'],
    deliveryPlatforms: ['Deliveroo', 'UberEats', 'JustEat', 'Own fleet'],
    foodTypes: ['street food', 'hot meals', 'bakery', 'healthy', 'fusion'],
    website: 'liverpoolstreetfoodlab.co.uk',
    phone: '0151 234 5678',
    email: 'hello@liverpoolstreetfoodlab.co.uk',
    description: 'Creative food incubator in Liverpool\'s Baltic Triangle. Great community, market access, and affordable hourly rates for startups and independents.',
    features: ['market access', 'food startup network', 'flexible booking', 'brand development workshops'],
    rating: 4.7,
    reviewCount: 93,
    verified: true,
  },
]
