/**
 * Migration script: Insert all hardcoded providers into Supabase
 * Run: bun scripts/migrate-providers.ts
 */

import { createClient } from '@supabase/supabase-js'

const SUPABASE_URL = 'https://vmuprcheuqnawtlzdyds.supabase.co'
const SERVICE_ROLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtdXByY2hldXFuYXd0bHpkeWRzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MjY1NzE0OCwiZXhwIjoyMDg4MjMzMTQ4fQ.lqT35WHjWYDlzS4GUJDNQo_XWEdqcr4Q6eONSrkg8wk'

const supabase = createClient(SUPABASE_URL, SERVICE_ROLE_KEY)

// -----------------------------------------------------------------------
// MERGED provider list from both route.ts and browse/[category]/page.tsx
// Fields from route.ts take priority; browse page provides priceRange & extra entries
// -----------------------------------------------------------------------
const PROVIDERS = [
  // ─── DARK KITCHENS ────────────────────────────────────────────────────
  {
    id: 'karma-kitchen',
    name: 'Karma Kitchen',
    type: 'dark_kitchen',
    cities: ['London', 'Manchester', 'Birmingham'],
    price_min: 3200,
    price_max: 10000,
    price_unit: 'month',
    price_range: '£3,200-10,000/mo',
    equipment: ['Deep fat fryers', 'Commercial oven', 'Gas hobs / Range', 'Extraction / Ventilation', 'Walk-in cold room', 'Prep tables'],
    features: ['24hr access', 'Flexible terms', 'Delivery partnerships', 'All utilities included'],
    best_for_business: ['delivery_only', 'dark_kitchen'],
    best_for_scale: ['medium', 'large'],
    best_for_budget: ['2000-5000', '5000+'],
    cuisine_strength: ['Burgers', 'Chicken & Chips', 'Indian', 'Caribbean', 'Chinese'],
    website: 'https://karmakitchen.co',
    description: 'Fully-equipped dark kitchen spaces with delivery platform partnerships. Ideal for established delivery brands looking to scale.',
    active: true,
    verified: true,
  },
  {
    id: 'deliveroo-editions',
    name: 'Deliveroo Editions',
    type: 'dark_kitchen',
    cities: ['London', 'Manchester', 'Birmingham', 'Leeds', 'Bristol', 'Edinburgh', 'Glasgow', 'Liverpool', 'Nottingham'],
    price_min: 4800,
    price_max: 14000,
    price_unit: 'month',
    price_range: '£4,800-14,000/mo',
    equipment: ['Deep fat fryers', 'Commercial oven', 'Gas hobs / Range', 'Extraction / Ventilation', 'Walk-in cold room'],
    features: ['Deliveroo partnership', 'High footfall areas', 'Marketing support', 'Data insights', 'Exclusive delivery zones'],
    best_for_business: ['delivery_only'],
    best_for_scale: ['large', 'enterprise'],
    best_for_budget: ['5000+'],
    cuisine_strength: ['Burgers', 'Chicken & Chips', 'Pizza', 'Indian', 'Chinese', 'Mexican'],
    website: 'https://restaurants.deliveroo.com/en-gb/editions',
    description: 'Premium dark kitchen sites in high-demand delivery areas. Best for brands with proven track record seeking rapid expansion.',
    active: true,
    verified: true,
  },
  {
    id: 'foodstars',
    name: 'FoodStars (CloudKitchens)',
    type: 'dark_kitchen',
    cities: ['London'],
    price_min: 1800,
    price_max: 4500,
    price_unit: 'month',
    price_range: '£1,800-4,500/mo',
    equipment: ['Deep fat fryers', 'Commercial oven', 'Gas hobs / Range', 'Upright fridge', 'Upright freezer'],
    features: ['100+ London locations', 'Flexible contracts', 'Basic equipment included', 'Shared facilities'],
    best_for_business: ['delivery_only', 'starting'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['1000-2000', '2000-5000'],
    cuisine_strength: ['Burgers', 'Chicken & Chips', 'Pizza', 'Healthy / Salads'],
    website: 'https://www.cloudkitchens.com',
    description: 'Affordable entry-level dark kitchen spaces across London. Good for testing delivery concepts with lower commitment.',
    active: true,
    verified: false,
  },
  {
    id: 'jacuna-kitchens',
    name: 'Jacuna Kitchens',
    type: 'dark_kitchen',
    cities: ['London', 'Birmingham', 'Leeds', 'Manchester', 'Bristol'],
    price_min: 2500,
    price_max: 6000,
    price_unit: 'month',
    price_range: '£2,500-6,000/mo',
    equipment: ['Deep fat fryers', 'Commercial oven', 'Gas hobs / Range', 'Extraction / Ventilation', 'Prep tables'],
    features: ['Multi-platform delivery', 'Flexible terms', '3-month minimum'],
    best_for_business: ['delivery_only'],
    best_for_scale: ['medium', 'large'],
    best_for_budget: ['2000-5000'],
    cuisine_strength: ['Indian', 'Caribbean', 'Turkish / Kebabs', 'Chinese'],
    website: 'https://www.jacuna.co.uk',
    description: 'Growing dark kitchen network with sites across major UK cities. Good mid-range option for delivery brands.',
    active: true,
    verified: false,
  },
  {
    id: 'chefs-lab',
    name: 'Chefs Lab',
    type: 'dark_kitchen',
    cities: ['Birmingham'],
    price_min: 1500,
    price_max: 4000,
    price_unit: 'month',
    price_range: '£1,500-4,000/mo',
    equipment: ['Commercial oven', 'Gas hobs / Range', 'Deep fat fryers', 'Extraction / Ventilation', 'Prep tables'],
    features: ['Deliveroo & Uber Eats ready', 'Flexible terms', 'WhatsApp support', 'Ghost kitchen setup'],
    best_for_business: ['delivery_only', 'dark_kitchen'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['1000-2000', '2000-5000'],
    cuisine_strength: ['Burgers', 'Chicken & Chips', 'Indian', 'Caribbean', 'Chinese'],
    website: 'https://chefslab.co.uk',
    description: 'Commercial dark kitchens in Birmingham. Purpose-built for Deliveroo, Uber Eats, and ghost kitchen operations.',
    active: true,
    verified: false,
  },
  {
    id: 'ready-kitchen',
    name: 'Ready Kitchen',
    type: 'dark_kitchen',
    cities: ['London'],
    price_min: 2000,
    price_max: 4500,
    price_unit: 'month',
    price_range: '£2,000-4,500/mo',
    equipment: ['Commercial oven', 'Gas hobs / Range', 'Deep fat fryers', 'Extraction / Ventilation', 'Prep tables', 'Upright fridge'],
    features: ['Canary Wharf location', 'Turnkey solution', 'Delivery-only', 'High demand area', 'Online ordering tech'],
    best_for_business: ['delivery_only', 'dark_kitchen'],
    best_for_scale: ['small', 'medium', 'large'],
    best_for_budget: ['2000-5000'],
    cuisine_strength: ['Burgers', 'Chicken & Chips', 'Indian', 'Chinese', 'Healthy / Salads'],
    website: 'https://www.readykitchen.co.uk',
    description: "Turnkey dark kitchens in Canary Wharf — one of London's highest delivery demand areas.",
    active: true,
    verified: false,
  },
  {
    id: 'one-kcn',
    name: 'One KCN',
    type: 'dark_kitchen',
    cities: ['London'],
    price_min: 1800,
    price_max: 5000,
    price_unit: 'month',
    price_range: '£1,800-5,000/mo',
    equipment: ['Commercial oven', 'Gas hobs / Range', 'Deep fat fryers', 'Extraction / Ventilation', 'Prep tables', 'Upright fridge', 'Upright freezer'],
    features: ['State-of-the-art', 'Equipment packages available', 'SW6 premium location', '30 years catering experience', 'High-speed internet', 'Fire & security'],
    best_for_business: ['delivery_only', 'dark_kitchen', 'catering', 'production'],
    best_for_scale: ['small', 'medium', 'large'],
    best_for_budget: ['1000-2000', '2000-5000'],
    cuisine_strength: ['Indian', 'Chinese', 'Burgers', 'Healthy / Salads', 'Mediterranean', 'Caribbean'],
    website: 'https://www.onekcn.com',
    description: "Premium ghost kitchens in Fulham, SW6. 7 high-end kitchens in one of London's highest delivery demand areas.",
    active: true,
    verified: false,
  },
  {
    id: 'boxb-bristol',
    name: 'BoxB.',
    type: 'dark_kitchen',
    cities: ['Bristol'],
    price_min: 1200,
    price_max: 3000,
    price_unit: 'month',
    price_range: '£1,200-3,000/mo',
    equipment: ['6-burner gas range', 'Gas interlocked canopy extraction', 'Commercial fridge', 'Commercial freezer', 'Pot wash / rinse station', 'Hand wash station', 'Stainless steel prep tables'],
    features: ['Short-term contracts', 'Shipping container units', 'Delivery-optimised', 'Low overheads', 'No long-term commitment', 'Customisable setup'],
    best_for_business: ['delivery_only', 'dark_kitchen', 'production'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['1000-2000', '2000-5000'],
    cuisine_strength: ['all'],
    website: 'https://www.boxb.co.uk',
    description: 'Central Bristol dark kitchens in converted shipping container units. Purpose-built for delivery brands — low cost, short contracts, fast setup.',
    active: true,
    verified: false,
  },
  {
    id: 'ghost-x-kitchens',
    name: 'Ghost x Kitchens',
    type: 'dark_kitchen',
    cities: ['London', 'Manchester', 'Birmingham', 'Leeds', 'Liverpool'],
    price_min: 1800,
    price_max: 4500,
    price_unit: 'month',
    price_range: '£1,800-4,500/mo',
    equipment: ['Deep fat fryers', 'Commercial oven', 'Gas hobs / Range', 'Extraction / Ventilation'],
    features: ['Modern facilities', 'Flexible terms', 'Delivery platform support', 'Digital-first approach'],
    best_for_business: ['delivery_only', 'dark_kitchen'],
    best_for_scale: ['small', 'medium', 'large'],
    best_for_budget: ['1000-2000', '2000-5000'],
    cuisine_strength: ['Burgers', 'Chicken & Chips', 'Pizza', 'Indian', 'Chinese'],
    website: 'https://ghostxkitchens.co.uk',
    description: 'Modern dark kitchen spaces for digital-first food brands. From startups to national chains.',
    active: true,
    verified: false,
  },
  {
    id: 'dephna',
    name: 'Dephna',
    type: 'dark_kitchen',
    cities: ['London'],
    price_min: 1500,
    price_max: 4000,
    price_unit: 'month',
    price_range: '£1,500-4,000/mo',
    equipment: ['Commercial oven', 'Gas hobs / Range', 'Walk-in cold room', 'Prep tables', 'Storage shelving'],
    features: ['8 London locations', 'Since 1972', 'Cold storage available', 'Flexible terms'],
    best_for_business: ['delivery_only', 'production', 'catering'],
    best_for_scale: ['small', 'medium', 'large'],
    best_for_budget: ['1000-2000', '2000-5000'],
    cuisine_strength: ['all'],
    website: 'https://dephna.com',
    description: 'Established London kitchen provider since 1972. Eight locations across North West London.',
    active: true,
    verified: false,
  },
  {
    id: 'encore-kitchens-manchester',
    name: 'Encore Kitchens Manchester',
    type: 'dark_kitchen',
    cities: ['Manchester'],
    price_min: 1500,
    price_max: 5000,
    price_unit: 'month',
    price_range: '£1,500-5,000/mo',
    equipment: ['Commercial oven', 'Gas hobs / Range', 'Deep fat fryers', 'Extraction / Ventilation', 'Walk-in cold room', 'Prep tables'],
    features: ['Delivery focused', '25+ UK locations', 'Flexible terms', 'Distribution support'],
    best_for_business: ['delivery_only', 'dark_kitchen', 'production'],
    best_for_scale: ['medium', 'large'],
    best_for_budget: ['1000-2000', '2000-5000', '5000+'],
    cuisine_strength: ['Burgers', 'Chicken & Chips', 'Indian', 'Chinese', 'all'],
    website: 'https://www.encorekitchens.co.uk',
    description: "Part of the UK's largest commercial kitchen network with 550+ kitchens. Delivery kitchens across Manchester.",
    active: true,
    verified: false,
  },
  // Browse-only dark kitchens
  {
    id: 'papi-kitchens',
    name: 'Papi Kitchens',
    type: 'dark_kitchen',
    cities: ['London'],
    price_min: 2000,
    price_max: 4000,
    price_unit: 'month',
    price_range: '£2,000-4,000/mo',
    equipment: ['Commercial oven', 'Gas hobs / Range', 'Deep fat fryers', 'Extraction / Ventilation'],
    features: ['East London', 'Community focus', 'Flexible terms'],
    best_for_business: ['delivery_only', 'dark_kitchen'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['2000-5000'],
    cuisine_strength: ['all'],
    website: 'https://papikitchens.com',
    description: 'East London dark kitchens with a community focus.',
    active: true,
    verified: false,
  },
  {
    id: 'the-co-kitchens',
    name: 'The Co-Kitchens',
    type: 'dark_kitchen',
    cities: ['London'],
    price_min: 1200,
    price_max: 4000,
    price_unit: 'month',
    price_range: '£1,200-4,000/mo',
    equipment: ['Commercial oven', 'Gas hobs / Range', 'Prep tables', 'Storage shelving', 'Upright fridge', 'Upright freezer'],
    features: ['Community focused', 'Natural lighting', 'Flexible hours', 'R&D friendly', 'Bring your own equipment'],
    best_for_business: ['starting', 'production', 'catering', 'dark_kitchen'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['1000-2000', '2000-5000'],
    cuisine_strength: ['Desserts & Bakery', 'Healthy / Salads', 'Mediterranean', 'Italian / Pasta'],
    website: 'https://theco-kitchens.com',
    description: 'Community-focused cloud kitchen with great natural lighting and flexible hours. Popular for R&D and product development.',
    active: true,
    verified: false,
  },
  {
    id: 'growth-kitchen',
    name: 'Growth Kitchen',
    type: 'dark_kitchen',
    cities: ['London', 'Nationwide'],
    price_min: 2000,
    price_max: 5000,
    price_unit: 'month',
    price_range: '£2,000-5,000/mo',
    equipment: ['Commercial oven', 'Gas hobs / Range', 'Deep fat fryers', 'Extraction / Ventilation'],
    features: ['Satellite kitchen network', 'Established brand partners', 'Flexible terms'],
    best_for_business: ['delivery_only', 'dark_kitchen'],
    best_for_scale: ['medium', 'large'],
    best_for_budget: ['2000-5000'],
    cuisine_strength: ['all'],
    website: 'https://growthkitchen.com',
    description: 'Satellite kitchen network for established brands. Tortilla, Tai Kitchen and others use Growth Kitchen.',
    active: true,
    verified: false,
  },

  // ─── SHARED KITCHENS ──────────────────────────────────────────────────
  {
    id: 'mission-kitchen',
    name: 'Mission Kitchen',
    type: 'shared_kitchen',
    cities: ['London'],
    price_min: 15,
    price_max: 45,
    price_unit: 'hour',
    price_range: '£15-45/hr',
    equipment: ['Commercial oven', 'Gas hobs / Range', 'Prep tables', 'Storage shelving', 'Mixer', 'Food processor'],
    features: ['Social enterprise', 'Business support', 'Memberships available', 'Community focus', 'Training programmes'],
    best_for_business: ['starting', 'home', 'popup', 'catering', 'production'],
    best_for_scale: ['small'],
    best_for_budget: ['under-500', '500-1000'],
    cuisine_strength: ['Desserts & Bakery', 'Healthy / Salads', 'Breakfast & Brunch', 'Coffee & Café'],
    website: 'https://missionkitchen.org',
    description: 'Social enterprise offering affordable hourly kitchen access. Perfect for food startups, home bakers scaling up, and caterers.',
    active: true,
    verified: true,
  },
  {
    id: 'sharethere',
    name: 'ShareThere',
    type: 'shared_kitchen',
    cities: ['London', 'Manchester', 'Birmingham', 'Bristol', 'Leeds'],
    price_min: 18,
    price_max: 85,
    price_unit: 'hour',
    price_range: '£18-85/hr',
    equipment: ['Commercial oven', 'Prep tables', 'Storage', 'Upright fridge', 'Upright freezer'],
    features: ['Online booking', 'Flexible hours', 'Multiple locations', 'No long contracts'],
    best_for_business: ['starting', 'home', 'catering', 'popup'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['under-500', '500-1000', '1000-2000'],
    cuisine_strength: ['Desserts & Bakery', 'Breakfast & Brunch', 'Italian / Pasta', 'Healthy / Salads'],
    website: 'https://sharethere.co',
    description: 'Book commercial kitchen space by the hour across the UK. Ideal for caterers, pop-up chefs, and food producers.',
    active: true,
    verified: false,
  },
  {
    id: 'sharedining',
    name: 'ShareDining',
    type: 'shared_kitchen',
    cities: ['London', 'Leeds'],
    price_min: 15,
    price_max: 50,
    price_unit: 'hour',
    price_range: '£15-50/hr',
    equipment: ['Commercial oven', 'Gas hobs / Range', 'Prep tables', 'Upright fridge'],
    features: ['Schools & church halls', 'Cafes & restaurants', 'Flexible hourly', 'Online booking', 'Affordable'],
    best_for_business: ['starting', 'home', 'catering', 'popup', 'production'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['under-500', '500-1000', '1000-2000'],
    cuisine_strength: ['all'],
    website: 'https://sharedining.co.uk',
    description: 'Kitchen marketplace listing spaces in schools, church halls, cafes and restaurants. Flexible hourly booking.',
    active: true,
    verified: false,
  },
  {
    id: 'n4-kitchen-hire',
    name: 'N4 Kitchen Hire',
    type: 'shared_kitchen',
    cities: ['London'],
    price_min: 15,
    price_max: 35,
    price_unit: 'hour',
    price_range: '£15-35/hr',
    equipment: ['Commercial oven', 'Gas hobs / Range', 'Prep tables', 'Upright fridge', 'Upright freezer'],
    features: ['5-star hygiene rating', '24hr access', 'Loading bays', 'Free parking', 'Free WiFi', 'Short & long term'],
    best_for_business: ['starting', 'catering', 'popup', 'production', 'delivery_only'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['under-500', '500-1000'],
    cuisine_strength: ['Burgers', 'Indian', 'Caribbean', 'Chinese', 'Desserts & Bakery'],
    website: 'https://www.n4kitchenhire.co.uk',
    description: 'Affordable hourly kitchen hire in North London (N4). 5-star hygiene, 24hr access, 4 miles from central London.',
    active: true,
    verified: true,
  },
  {
    id: 'ncass-kitchen',
    name: 'NCASS Production Kitchen',
    type: 'shared_kitchen',
    cities: ['Birmingham', 'Leeds'],
    price_min: 20,
    price_max: 150,
    price_unit: 'hour',
    price_range: '£20-150/hr',
    equipment: ['Commercial oven', 'Deep fat fryers', 'Gas hobs / Range', 'Walk-in cold room', 'Blast chiller', 'Prep tables'],
    features: ['Industry body facility', 'Training available', 'Member discounts', 'Large scale production'],
    best_for_business: ['production', 'catering'],
    best_for_scale: ['medium', 'large'],
    best_for_budget: ['1000-2000', '2000-5000'],
    cuisine_strength: ['Burgers', 'Chicken & Chips', 'Fish & Chips', 'Breakfast & Brunch'],
    website: 'https://ncass.org.uk',
    description: 'Professional production kitchen run by the National Caterers Association. Ideal for large-scale food production and events.',
    active: true,
    verified: true,
  },
  {
    id: 'maida-hill-place',
    name: 'Maida Hill Place',
    type: 'shared_kitchen',
    cities: ['London'],
    price_min: 15,
    price_max: 40,
    price_unit: 'hour',
    price_range: '£15-40/hr',
    equipment: ['Commercial oven', 'Gas hobs / Range', 'Mixer', 'Prep tables'],
    features: ['Westminster location', 'Business development', 'Affordable rates', 'Community kitchen'],
    best_for_business: ['starting', 'home', 'popup'],
    best_for_scale: ['small'],
    best_for_budget: ['under-500', '500-1000'],
    cuisine_strength: ['Desserts & Bakery', 'Caribbean', 'Healthy / Salads'],
    website: 'https://www.maidahillplace.co.uk',
    description: 'Community kitchen in Westminster supporting food startups. Low overheads and business development support included.',
    active: true,
    verified: false,
  },
  {
    id: 'encore-kitchens',
    name: 'Encore Kitchens',
    type: 'shared_kitchen',
    cities: ['London', 'Birmingham', 'Manchester'],
    price_min: 150,
    price_max: 400,
    price_unit: 'day',
    price_range: '£150-400/day',
    equipment: ['Commercial oven', 'Walk-in cold room', 'Blast chiller', 'Prep tables', 'Mixer'],
    features: ['Day rate available', 'Multiple London sites', 'Large production spaces', 'Professional grade'],
    best_for_business: ['production', 'catering'],
    best_for_scale: ['medium', 'large'],
    best_for_budget: ['1000-2000', '2000-5000'],
    cuisine_strength: ['all'],
    website: 'https://encorekitchens.co.uk',
    description: 'Day-rate production kitchens across London, Birmingham and Manchester. Professional facilities for serious producers.',
    active: true,
    verified: false,
  },
  {
    id: 'cooking-it-bristol',
    name: 'Cooking It',
    type: 'shared_kitchen',
    cities: ['Bristol'],
    price_min: 15,
    price_max: 45,
    price_unit: 'hour',
    price_range: '£15-45/hr',
    equipment: ['Commercial oven', 'Gas hobs / Range', 'Prep tables', 'Upright fridge', 'Upright freezer'],
    features: ['Event space', 'Filming available', 'Pop-up ready', 'Ghost kitchen use'],
    best_for_business: ['starting', 'popup', 'catering', 'production'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['under-500', '500-1000', '1000-2000'],
    cuisine_strength: ['all'],
    website: 'https://cookingit.co.uk',
    description: 'Versatile commercial kitchen in Bristol for production, filming, pop-ups and ghost kitchen use.',
    active: true,
    verified: false,
  },
  {
    id: 'cloud-kingdom-bristol',
    name: 'Cloud Kingdom Kitchen',
    type: 'shared_kitchen',
    cities: ['Bristol'],
    price_min: 12,
    price_max: 35,
    price_unit: 'hour',
    price_range: '£12-35/hr',
    equipment: ['Commercial oven', 'Gas hobs / Range', 'Prep tables', 'Storage'],
    features: ['Central location', 'Affordable', 'Flexible hours'],
    best_for_business: ['starting', 'catering', 'popup'],
    best_for_scale: ['small'],
    best_for_budget: ['under-500', '500-1000'],
    cuisine_strength: ['all'],
    website: 'https://cloudkingdomkitchenhire.co.uk',
    description: 'Affordable commercial kitchen and prep space in central Bristol. Flexible hourly hire.',
    active: true,
    verified: false,
  },
  {
    id: 'coexist-bristol',
    name: 'Coexist Community Kitchen',
    type: 'shared_kitchen',
    cities: ['Bristol'],
    price_min: 10,
    price_max: 30,
    price_unit: 'hour',
    price_range: '£10-30/hr',
    equipment: ['Commercial oven', 'Gas hobs / Range', 'Prep tables', 'Upright fridge'],
    features: ['Community focused', 'Workshops', 'Affordable', 'Social enterprise'],
    best_for_business: ['starting', 'catering', 'popup'],
    best_for_scale: ['small'],
    best_for_budget: ['under-500', '500-1000'],
    cuisine_strength: ['all'],
    website: 'https://www.coexistcommunitykitchen.org',
    description: 'Community kitchen supporting local food businesses. Every hire supports community meals and classes.',
    active: true,
    verified: false,
  },
  {
    id: 'centre-for-life-newcastle',
    name: 'Centre for Life Kitchen',
    type: 'shared_kitchen',
    cities: ['Newcastle'],
    price_min: 20,
    price_max: 50,
    price_unit: 'hour',
    price_range: '£20-50/hr',
    equipment: ['Commercial oven', 'Gas hobs / Range', 'Dishwasher', 'Prep tables', 'Walk-in cold room'],
    features: ['City centre', '140 sqm space', 'Modern equipment', 'Professional grade'],
    best_for_business: ['production', 'catering', 'popup'],
    best_for_scale: ['medium', 'large'],
    best_for_budget: ['1000-2000', '2000-5000'],
    cuisine_strength: ['all'],
    website: 'https://life.org.uk',
    description: 'Large 140sqm professional kitchen in Newcastle city centre. Modern equipment and excellent facilities.',
    active: true,
    verified: false,
  },
  // Browse-only shared kitchens
  {
    id: 'fulham-kitchen',
    name: 'Fulham Kitchen',
    type: 'shared_kitchen',
    cities: ['London'],
    price_min: 20,
    price_max: 50,
    price_unit: 'hour',
    price_range: '£20-50/hr',
    equipment: ['Commercial oven', 'Gas hobs / Range', 'Prep tables', 'Upright fridge'],
    features: ['West London', 'Flexible hours', 'Good facilities'],
    best_for_business: ['starting', 'catering', 'popup'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['under-500', '500-1000'],
    cuisine_strength: ['all'],
    website: 'https://fulhamkitchen.co.uk',
    description: 'West London shared kitchen for caterers and food startups.',
    active: true,
    verified: false,
  },
  {
    id: 'northern-kitchen-hire',
    name: 'Northern Kitchen Hire',
    type: 'shared_kitchen',
    cities: ['Leeds'],
    price_min: 15,
    price_max: 35,
    price_unit: 'hour',
    price_range: '£15-35/hr',
    equipment: ['Commercial oven', 'Gas hobs / Range', 'Walk-in cold room', 'Combi oven', 'Brat pan'],
    features: ['2500 sq ft', 'Walk-in fridge', 'Combi oven', 'Brat pan'],
    best_for_business: ['production', 'catering'],
    best_for_scale: ['medium', 'large'],
    best_for_budget: ['500-1000', '1000-2000'],
    cuisine_strength: ['all'],
    website: 'https://ncass.org.uk/commercial-kitchen-spaces-to-rent',
    description: '2500 sq ft kitchens. Walk-in fridge, combi oven, brat pan.',
    active: true,
    verified: false,
  },

  // ─── FOOD HALLS / MARKETS ─────────────────────────────────────────────
  {
    id: 'appear-here',
    name: 'Appear Here',
    type: 'food_hall',
    cities: ['London', 'Manchester', 'Birmingham', 'Bristol', 'Edinburgh', 'Glasgow', 'Leeds', 'Liverpool', 'Brighton', 'Nationwide'],
    price_min: 500,
    price_max: 5000,
    price_unit: 'week',
    price_range: '£500-5,000/week',
    equipment: [],
    features: ['Online booking', 'Flexible terms', 'Pop-up ready spaces', 'Market stalls available', 'Food & beverage collection', 'Short-term rentals'],
    best_for_business: ['popup', 'starting', 'retail'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['500-1000', '1000-2000', '2000-5000'],
    cuisine_strength: ['Coffee & Café', 'Desserts & Bakery', 'Street Food', 'Healthy / Salads'],
    website: 'https://www.appearhere.co.uk',
    description: "UK's leading marketplace for short-term retail and food spaces. Book online like Airbnb — instant availability, flexible terms from 1 day to 1 year.",
    active: true,
    verified: true,
  },
  {
    id: 'mercato-metropolitano',
    name: 'Mercato Metropolitano',
    type: 'food_hall',
    cities: ['London'],
    price_min: 2000,
    price_max: 6000,
    price_unit: 'month',
    price_range: '£2,000-6,000/mo',
    equipment: ['Basic kitchen setup', 'Shared prep areas'],
    features: ['Sustainable community market', 'High footfall', 'Events programme', 'Marketing support', 'Trader community'],
    best_for_business: ['popup', 'starting', 'retail'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['2000-5000'],
    cuisine_strength: ['Italian', 'Mediterranean', 'Pizza', 'Coffee & Café', 'Street Food', 'Vegan / Vegetarian'],
    website: 'https://mercatometropolitano.com/traders-apply',
    description: "London's first sustainable community food market. Sites in Elephant & Castle and Mayfair.",
    active: true,
    verified: false,
  },
  {
    id: 'kerb-inkerbator',
    name: 'KERB InKERBator',
    type: 'food_hall',
    cities: ['London'],
    price_min: 0,
    price_max: 500,
    price_unit: 'week',
    price_range: '£0-500/week',
    equipment: [],
    features: ['8-week mentorship programme', 'Market pitch included', 'Business coaching', 'Feedback & support', '78% graduate to full membership', 'Quarterly intake'],
    best_for_business: ['starting', 'popup'],
    best_for_scale: ['small'],
    best_for_budget: ['under-500', '500-1000'],
    cuisine_strength: ['Street Food', 'Burgers', 'Mexican', 'Asian', 'Caribbean', 'Middle Eastern'],
    website: 'https://www.kerbfood.com/inkerbator',
    description: "London's premier street food incubator. Apply quarterly for the 8-week programme — mentorship, market access, and path to trading at KERB locations.",
    active: true,
    verified: true,
  },
  {
    id: 'tooting-market',
    name: 'Tooting Market',
    type: 'food_hall',
    cities: ['London'],
    price_min: 120,
    price_max: 300,
    price_unit: 'week',
    price_range: '£120-300/week',
    equipment: [],
    features: ['Historic South London market', 'Strong local community', 'Diverse food scene', 'Affordable entry', 'Direct application'],
    best_for_business: ['starting', 'popup', 'retail'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['under-500', '500-1000'],
    cuisine_strength: ['Caribbean', 'African', 'Indian', 'Street Food', 'Coffee & Café'],
    website: 'https://tootingmarket.com',
    description: 'Vibrant South London indoor market with affordable stalls from £120/week.',
    active: true,
    verified: false,
  },
  {
    id: 'oya-kitchens',
    name: 'Oya',
    type: 'food_hall',
    cities: ['London', 'Manchester', 'Birmingham', 'Bristol', 'Leeds', 'Liverpool', 'Derby', 'Nottingham', 'Leicester', 'Nationwide'],
    price_min: 500,
    price_max: 3000,
    price_unit: 'month',
    price_range: '£500-3,000/mo',
    equipment: ['Fully equipped kitchens', 'Varies by venue'],
    features: ['Pub residencies', 'Restaurant spaces', 'Marketplace platform', 'Viewings via app', 'Expert negotiation support', 'Customer-facing venues'],
    best_for_business: ['popup', 'starting', 'catering', 'retail'],
    best_for_scale: ['small', 'medium', 'large'],
    best_for_budget: ['500-1000', '1000-2000', '2000-5000'],
    cuisine_strength: ['Burgers', 'Street Food', 'Pub Food', 'Pizza', 'Chicken & Chips'],
    website: 'https://www.oya.co.uk',
    description: 'Property marketplace for the food industry. Browse pubs, restaurants and commercial spaces looking for food operators.',
    active: true,
    verified: false,
  },
  {
    id: 'spaceandpeople',
    name: 'SpaceandPeople',
    type: 'food_hall',
    cities: ['London', 'Manchester', 'Birmingham', 'Glasgow', 'Edinburgh', 'Leeds', 'Nationwide'],
    price_min: 300,
    price_max: 2000,
    price_unit: 'week',
    price_range: '£300-2,000/week',
    equipment: ['Kiosks available', 'Mobile units', 'Mall spaces'],
    features: ['Shopping centre kiosks', 'Train station pitches', 'High footfall locations', 'Rock Up & Pop Up programme', 'Network Rail stations'],
    best_for_business: ['popup', 'retail', 'starting'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['500-1000', '1000-2000', '2000-5000'],
    cuisine_strength: ['Coffee & Café', 'Street Food', 'Desserts & Bakery', 'Healthy / Salads'],
    website: 'https://www.spaceandpeople.co.uk',
    description: 'Access to shopping centres and train stations across UK. Kiosks, pop-up spaces, and mall pitches with massive footfall.',
    active: true,
    verified: false,
  },
  {
    id: 'street-food-warehouse',
    name: 'Street Food Warehouse',
    type: 'food_hall',
    cities: ['Nationwide'],
    price_min: 0,
    price_max: 500,
    price_unit: 'month',
    price_range: '£0-500/event',
    equipment: ['Bring your own setup'],
    features: ['Festival pitches', 'Private event bookings', 'Wedding catering leads', 'Corporate events', 'Free trader database'],
    best_for_business: ['mobile', 'popup', 'catering'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['under-500', '500-1000'],
    cuisine_strength: ['Street Food', 'Burgers', 'BBQ', 'Mexican', 'Asian'],
    website: 'https://streetfoodwarehouse.co.uk/apply-to-trade/',
    description: 'Festival and event trader network. Join their free database to get pitched for weddings, corporate events, and festivals nationwide.',
    active: true,
    verified: false,
  },
  {
    id: 'great-british-food-festival',
    name: 'Great British Food Festival',
    type: 'food_hall',
    cities: ['Nationwide'],
    price_min: 128,
    price_max: 400,
    price_unit: 'day',
    price_range: '£128-400/day',
    equipment: ['Bring your own setup'],
    features: ['2,000-6,000 visitors per day', 'Multiple events annually', 'Historic venue locations', 'Producer and trader pitches'],
    best_for_business: ['mobile', 'popup', 'catering'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['under-500', '500-1000'],
    cuisine_strength: ['Street Food', 'British', 'BBQ', 'Artisan'],
    website: 'https://greatbritishfoodfestival.com/traders/',
    description: 'UK food festival circuit with pitches from £128/day. Events at stately homes and venues across the country.',
    active: true,
    verified: false,
  },
  {
    id: 'storefront',
    name: 'Storefront',
    type: 'food_hall',
    cities: ['London', 'Manchester', 'Birmingham', 'Nationwide'],
    price_min: 100,
    price_max: 2000,
    price_unit: 'day',
    price_range: '£100-2,000/day',
    equipment: ['Varies by space'],
    features: ['Short-term rentals', 'Market stalls', 'Kiosks', 'Food truck pitches', 'Online marketplace'],
    best_for_business: ['popup', 'starting', 'retail'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['under-500', '500-1000', '1000-2000'],
    cuisine_strength: ['Street Food', 'Coffee & Café', 'Desserts & Bakery'],
    website: 'https://www.thestorefront.com',
    description: 'Global marketplace for short-term retail spaces. Find food stalls, kiosks, and market pitches for pop-ups.',
    active: true,
    verified: false,
  },
  {
    id: 'digbeth-dining-club',
    name: 'Digbeth Dining Club',
    type: 'food_hall',
    cities: ['Birmingham', 'West Midlands'],
    price_min: 100,
    price_max: 300,
    price_unit: 'month',
    price_range: '£100-300/event',
    equipment: ['Bring your own setup'],
    features: ['Award-winning events', 'Street food focus', 'Midlands-based', 'Regular events', 'Growing venue network'],
    best_for_business: ['mobile', 'popup'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['under-500', '500-1000'],
    cuisine_strength: ['Street Food', 'Burgers', 'BBQ', 'Asian', 'Mexican'],
    website: 'https://digbethdiningclub.com/',
    description: 'Multi-award-winning Birmingham street food organisation. Apply to trade at their events.',
    active: true,
    verified: false,
  },
  {
    id: 'leeds-kirkgate',
    name: 'Leeds Kirkgate Market',
    type: 'food_hall',
    cities: ['Leeds'],
    price_min: 50,
    price_max: 200,
    price_unit: 'week',
    price_range: '£50-200/week',
    equipment: ['Basic stall setup'],
    features: ["One of Europe's largest indoor markets", 'New trader incentive', 'Council-run', 'High footfall', 'Historic venue'],
    best_for_business: ['starting', 'popup', 'retail'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['under-500', '500-1000'],
    cuisine_strength: ['Street Food', 'British', 'International', 'Coffee & Café'],
    website: 'https://markets.leeds.gov.uk/trade-our-markets/trade-kirkgate-market',
    description: 'Historic Leeds market with new trader incentive: 2 weeks half price, 2 weeks free! Council-run with transparent process.',
    active: true,
    verified: false,
  },
  {
    id: 'st-nicholas-bristol',
    name: 'St Nicholas Market Bristol',
    type: 'food_hall',
    cities: ['Bristol'],
    price_min: 50,
    price_max: 200,
    price_unit: 'day',
    price_range: '£50-200/day',
    equipment: ['Basic setup provided'],
    features: ['Iconic Bristol venue', 'Street food market', 'Indies market', 'Corn Exchange', 'Council-run'],
    best_for_business: ['starting', 'popup', 'mobile'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['under-500', '500-1000'],
    cuisine_strength: ['Street Food', 'International', 'Coffee & Café', 'Vegan / Vegetarian'],
    website: 'https://www.bristol.gov.uk/st-nicholas-markets/trade-with-us',
    description: "Bristol's iconic market with multiple trading options — Street Food Market, Indies Market, and Corn Exchange.",
    active: true,
    verified: false,
  },
  {
    id: 'edinburgh-markets',
    name: 'Stockbridge/Leith/Grassmarket',
    type: 'food_hall',
    cities: ['Edinburgh'],
    price_min: 30,
    price_max: 150,
    price_unit: 'day',
    price_range: '£30-150/day',
    equipment: ['Bring your own setup'],
    features: ['Weekly markets', 'Three Edinburgh locations', 'Local and tourist mix', 'Artisan focus'],
    best_for_business: ['starting', 'popup', 'mobile'],
    best_for_scale: ['small'],
    best_for_budget: ['under-500'],
    cuisine_strength: ['Street Food', 'Scottish', 'Coffee & Café', 'Artisan'],
    website: 'https://www.stockbridgemarket.com',
    description: 'Popular Edinburgh markets across three locations. Same management, so success at one can lead to spots at others.',
    active: true,
    verified: false,
  },

  // ─── MOBILE UNIT SUPPLIERS ────────────────────────────────────────────
  {
    id: 'amobox',
    name: 'Amobox',
    type: 'mobile_supplier',
    cities: ['Nationwide'],
    price_min: 35000,
    price_max: 95000,
    price_unit: 'one_time',
    price_range: '£35,000-95,000',
    equipment: ['Custom built to spec'],
    features: ['Premium design', 'Bespoke builds', '10-16 week lead time', 'Award-winning designs'],
    best_for_business: ['mobile'],
    best_for_scale: ['medium', 'large'],
    best_for_budget: ['5000+'],
    cuisine_strength: ['Burgers', 'Pizza', 'Coffee & Café', 'Desserts & Bakery'],
    website: 'https://amobox.com',
    description: 'Premium custom food truck and trailer conversions. For brands wanting a standout, design-led mobile unit.',
    active: true,
    verified: false,
  },
  {
    id: 'jiffy-trucks',
    name: 'Jiffy Trucks',
    type: 'mobile_supplier',
    cities: ['Nationwide'],
    price_min: 18000,
    price_max: 55000,
    price_unit: 'one_time',
    price_range: '£18,000-55,000',
    equipment: ['Bain maries', 'Deep fat fryers', 'Flat griddle / Plancha', 'Gas hobs / Range'],
    features: ['Hot & cold options', 'Snack trucks', 'Burger vans', 'Quick turnaround'],
    best_for_business: ['mobile'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['2000-5000', '5000+'],
    cuisine_strength: ['Burgers', 'Chicken & Chips', 'Fish & Chips', 'Breakfast & Brunch'],
    website: 'https://cateringtrucks.co.uk',
    description: 'Specialist catering vehicle builder for hot food operations. Good value for traditional street food setups.',
    active: true,
    verified: false,
  },
  {
    id: 'ghst-ktchn',
    name: 'Ghst Ktchn',
    type: 'mobile_supplier',
    cities: ['Nationwide'],
    price_min: 30000,
    price_max: 75000,
    price_unit: 'one_time',
    price_range: '£30,000-75,000',
    equipment: ['Custom built to spec', 'Deep fat fryers', 'Flat griddle / Plancha', 'Gas hobs / Range'],
    features: ['Contemporary designs', 'Street food specialists', 'Festival ready', 'Instagram-worthy builds'],
    best_for_business: ['mobile'],
    best_for_scale: ['medium', 'large'],
    best_for_budget: ['2000-5000', '5000+'],
    cuisine_strength: ['Burgers', 'Pizza', 'Mexican', 'Coffee & Café', 'Desserts & Bakery'],
    website: 'https://ghstktchn.com',
    description: 'Modern street food vehicle conversions with contemporary aesthetic. Popular with festival vendors and urban food brands.',
    active: true,
    verified: false,
  },
  {
    id: 'tudor-trailers',
    name: 'Tudor Trailers',
    type: 'mobile_supplier',
    cities: ['Nationwide'],
    price_min: 15000,
    price_max: 45000,
    price_unit: 'one_time',
    price_range: '£15,000-45,000',
    equipment: ['Bain maries', 'Deep fat fryers', 'Flat griddle / Plancha', 'Commercial oven'],
    features: ['Established manufacturer', 'Wide range', 'Finance available', 'VCA approved'],
    best_for_business: ['mobile'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['1000-2000', '2000-5000', '5000+'],
    cuisine_strength: ['Burgers', 'Fish & Chips', 'Chicken & Chips', 'Breakfast & Brunch', 'Coffee & Café'],
    website: 'https://tudortrailers.co.uk',
    description: 'Long-established UK catering trailer manufacturer. Reliable builds with proven track record and wide equipment options.',
    active: true,
    verified: false,
  },
  {
    id: 'bistro-trailers',
    name: 'Bistro Trailers',
    type: 'mobile_supplier',
    cities: ['Nationwide'],
    price_min: 20000,
    price_max: 55000,
    price_unit: 'one_time',
    price_range: '£20,000-55,000',
    equipment: ['Commercial oven', 'Gas hobs / Range', 'Deep fat fryers', 'Flat griddle / Plancha', 'Extraction / Ventilation'],
    features: ['High-end finishes', 'European style', 'Bespoke options', 'Quick turnaround'],
    best_for_business: ['mobile'],
    best_for_scale: ['medium', 'large'],
    best_for_budget: ['2000-5000', '5000+'],
    cuisine_strength: ['Pizza', 'Italian / Pasta', 'Coffee & Café', 'Breakfast & Brunch', 'Burgers'],
    website: 'https://bistrotrailers.co.uk',
    description: 'Premium catering trailers with European-influenced designs. Quality builds suited for artisan food operations.',
    active: true,
    verified: false,
  },
  {
    id: 'ar-willis',
    name: 'A&R Willis',
    type: 'mobile_supplier',
    cities: ['Nationwide'],
    price_min: 12000,
    price_max: 45000,
    price_unit: 'one_time',
    price_range: '£12,000-45,000',
    equipment: ['Custom built to spec', 'VCA approved'],
    features: ['VCA approved', '20+ years experience', 'Family run', 'Container conversions'],
    best_for_business: ['mobile'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['1000-2000', '2000-5000', '5000+'],
    cuisine_strength: ['Burgers', 'Fish & Chips', 'Chicken & Chips', 'Breakfast & Brunch'],
    website: 'https://arwilliscateringtrailers.co.uk',
    description: 'Family-run VCA-approved trailer manufacturer with 20+ years experience. Quality builds at fair prices.',
    active: true,
    verified: false,
  },
  {
    id: 'towability',
    name: 'Towability',
    type: 'mobile_supplier',
    cities: ['Nationwide'],
    price_min: 20000,
    price_max: 65000,
    price_unit: 'one_time',
    price_range: '£20,000-65,000',
    equipment: ['Custom built to spec'],
    features: ['Citroen H-Van specialists', 'Vintage conversions', 'Eye-catching designs'],
    best_for_business: ['mobile'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['2000-5000', '5000+'],
    cuisine_strength: ['Coffee & Café', 'Pizza', 'Desserts & Bakery', 'Burgers'],
    website: 'https://towability.com',
    description: 'Specialists in Citroen H-Van and vintage vehicle conversions. Stand-out retro designs that draw crowds.',
    active: true,
    verified: false,
  },
  {
    id: 'maxi-mover',
    name: 'Maxi Mover',
    type: 'mobile_supplier',
    cities: ['Nationwide'],
    price_min: 25000,
    price_max: 65000,
    price_unit: 'one_time',
    price_range: '£25,000-65,000',
    equipment: ['Low-floor van base', 'Lightweight construction', 'Custom spec available'],
    features: ['Low-floor van specialists', 'Direct from manufacturer', 'Maximum payload', 'Hexlite lightweight materials', 'Type approved'],
    best_for_business: ['mobile'],
    best_for_scale: ['small', 'medium', 'large'],
    best_for_budget: ['2000-5000', '5000+'],
    cuisine_strength: ['Burgers', 'Fish & Chips', 'Chicken & Chips', 'Coffee & Café', 'Pizza'],
    website: 'https://www.maximover.co.uk',
    description: 'UK low-floor van manufacturer specialising in catering conversions. Revolutionary lightweight Hexlite materials maximise payload.',
    active: true,
    verified: false,
  },
  {
    id: 'raccoon-vehicles',
    name: 'Raccoon Vehicles',
    type: 'mobile_supplier',
    cities: ['Nationwide'],
    price_min: 35000,
    price_max: 100000,
    price_unit: 'one_time',
    price_range: '£35,000-100,000',
    equipment: ['Bespoke to spec', 'Premium materials', 'Full branding'],
    features: ['Premium bespoke builds', 'Exhibition vehicles', 'Sample trucks', 'Roadshow specialists', 'Full design service'],
    best_for_business: ['mobile'],
    best_for_scale: ['medium', 'large'],
    best_for_budget: ['5000+'],
    cuisine_strength: ['all'],
    website: 'https://www.raccoon.co.uk',
    description: 'High-end bespoke vehicle conversions for brands that demand excellence. Street food, exhibition, sampling — premium builds with full design service.',
    active: true,
    verified: false,
  },
  {
    id: '4sure-catering',
    name: '4Sure Catering',
    type: 'mobile_supplier',
    cities: ['Nationwide'],
    price_min: 15000,
    price_max: 60000,
    price_unit: 'one_time',
    price_range: '£15,000-60,000',
    equipment: ['Deep fat fryers', 'Commercial oven', 'Gas hobs / Range', 'Flat griddle / Plancha', 'Bain maries'],
    features: ['Trailers & vans', 'Full range', 'Established manufacturer', 'Detailed specs available', 'Finance options'],
    best_for_business: ['mobile'],
    best_for_scale: ['small', 'medium', 'large'],
    best_for_budget: ['1000-2000', '2000-5000', '5000+'],
    cuisine_strength: ['Burgers', 'Fish & Chips', 'Chicken & Chips', 'Breakfast & Brunch', 'Coffee & Café'],
    website: 'https://4sure.co.uk',
    description: 'Established catering trailer and van manufacturer with full product range. Detailed specs and guidance for new and experienced operators.',
    active: true,
    verified: false,
  },
  {
    id: 'catering-units',
    name: 'Catering Units UK',
    type: 'mobile_supplier',
    cities: ['Nationwide'],
    price_min: 10000,
    price_max: 35000,
    price_unit: 'one_time',
    price_range: '£10,000-35,000',
    equipment: ['Bain maries', 'Deep fat fryers', 'Flat griddle / Plancha'],
    features: ['25+ years experience', 'Family business', 'All sectors covered'],
    best_for_business: ['mobile'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['1000-2000', '2000-5000'],
    cuisine_strength: ['Burgers', 'Fish & Chips', 'Chicken & Chips', 'Breakfast & Brunch'],
    website: 'https://cateringunits.co.uk',
    description: 'Established family business with 25+ years in catering unit manufacturing. Reliable builds for all budgets.',
    active: true,
    verified: false,
  },
  {
    id: 'catering-van-conversions',
    name: 'Catering Van Conversions',
    type: 'mobile_supplier',
    cities: ['Nationwide'],
    price_min: 15000,
    price_max: 50000,
    price_unit: 'one_time',
    price_range: '£15,000-50,000',
    equipment: ['Deep fat fryers', 'Flat griddle / Plancha', 'Bain maries', 'Commercial oven'],
    features: ['Bespoke builds', 'Quick turnaround', 'All van types'],
    best_for_business: ['mobile'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['1000-2000', '2000-5000', '5000+'],
    cuisine_strength: ['Burgers', 'Fish & Chips', 'Chicken & Chips', 'Indian', 'Caribbean'],
    website: 'https://cateringvanconversions.com',
    description: 'Custom-built catering vans designed for your specific needs. Professional builds with good value pricing.',
    active: true,
    verified: false,
  },
  {
    id: 'premier-catering',
    name: 'Premier Catering Manufacture',
    type: 'mobile_supplier',
    cities: ['Nationwide'],
    price_min: 18000,
    price_max: 55000,
    price_unit: 'one_time',
    price_range: '£18,000-55,000',
    equipment: ['Custom built to spec', 'Deep fat fryers', 'Gas hobs / Range'],
    features: ['Full conversions', 'Trailer specialists', 'Commercial grade'],
    best_for_business: ['mobile'],
    best_for_scale: ['small', 'medium', 'large'],
    best_for_budget: ['2000-5000', '5000+'],
    cuisine_strength: ['Burgers', 'Fish & Chips', 'Chicken & Chips', 'Pizza'],
    website: 'https://commercialkitchencompany.co.uk',
    description: 'Specialist mobile catering van and trailer conversions. Commercial-grade builds for serious operators.',
    active: true,
    verified: false,
  },
  {
    id: 'the-big-coffee',
    name: 'The Big Coffee',
    type: 'mobile_supplier',
    cities: ['Nationwide'],
    price_min: 15000,
    price_max: 55000,
    price_unit: 'one_time',
    price_range: '£15,000-55,000',
    equipment: ['Custom built to spec', 'Piaggio specialists'],
    features: ['Piaggio Ape specialists', 'Horsebox conversions', 'Pizza trailers', 'UK warranty'],
    best_for_business: ['mobile'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['1000-2000', '2000-5000', '5000+'],
    cuisine_strength: ['Coffee & Café', 'Pizza', 'Desserts & Bakery'],
    website: 'https://thebigcoffee.com',
    description: 'Specialists in Piaggio Ape and horsebox conversions. Perfect for coffee, pizza and artisan concepts.',
    active: true,
    verified: false,
  },
  {
    id: 'karpatia-trucks',
    name: 'Karpatia Trucks',
    type: 'mobile_supplier',
    cities: ['Nationwide'],
    price_min: 12000,
    price_max: 45000,
    price_unit: 'one_time',
    price_range: '£12,000-45,000',
    equipment: ['Custom built to spec'],
    features: ['Horsebox specialists', 'Financing available', 'Website included', 'Business support'],
    best_for_business: ['mobile'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['1000-2000', '2000-5000'],
    cuisine_strength: ['Coffee & Café', 'Desserts & Bakery', 'Pizza'],
    website: 'https://karpatiatrucks.com',
    description: 'Horsebox conversion specialists with full business support package including financing and website.',
    active: true,
    verified: false,
  },
  {
    id: 'mobile-retail-group',
    name: 'Mobile Retail Group',
    type: 'mobile_supplier',
    cities: ['Nationwide'],
    price_min: 20000,
    price_max: 70000,
    price_unit: 'one_time',
    price_range: '£20,000-70,000',
    equipment: ['Custom built to spec'],
    features: ['Premium builds', 'Full branding', 'Trailer conversions', 'Corporate clients'],
    best_for_business: ['mobile'],
    best_for_scale: ['medium', 'large'],
    best_for_budget: ['2000-5000', '5000+'],
    cuisine_strength: ['Coffee & Café', 'Pizza', 'Burgers', 'Desserts & Bakery'],
    website: 'https://mobileretailgroup.com',
    description: 'Premium mobile catering conversions with full branding packages. Corporate and event specialists.',
    active: true,
    verified: false,
  },
  {
    id: 'coffee-latino',
    name: 'Coffee Latino',
    type: 'mobile_supplier',
    cities: ['Nationwide'],
    price_min: 8000,
    price_max: 35000,
    price_unit: 'one_time',
    price_range: '£8,000-35,000',
    equipment: ['Coffee machines', 'Custom fit-out'],
    features: ['Horsebox specialists', 'Coffee focus', 'Supply your own vehicle option'],
    best_for_business: ['mobile'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['500-1000', '1000-2000', '2000-5000'],
    cuisine_strength: ['Coffee & Café'],
    website: 'https://coffeelatino.co.uk',
    description: 'Coffee-focused horsebox conversions. Supply your own vehicle or buy complete. Great entry prices.',
    active: true,
    verified: false,
  },
  {
    id: 'pizza-trailer-co',
    name: 'Wood Fired Pizza Ovens UK',
    type: 'mobile_supplier',
    cities: ['Nationwide'],
    price_min: 18000,
    price_max: 50000,
    price_unit: 'one_time',
    price_range: '£18,000-50,000',
    equipment: ['Pizza oven', 'Custom built to spec'],
    features: ['Wood-fired specialists', 'Trailer builds', 'Van conversions', 'Training included'],
    best_for_business: ['mobile'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['2000-5000', '5000+'],
    cuisine_strength: ['Pizza'],
    website: 'https://wood-fired-pizza-ovens.co.uk/mobile-pizza-ovens/',
    description: 'Specialist pizza trailer and van conversions with wood-fired oven options. Training included.',
    active: true,
    verified: false,
  },
  // Browse-only mobile suppliers
  {
    id: 'food-truck-masters',
    name: 'Food Truck Masters',
    type: 'mobile_supplier',
    cities: ['Nationwide'],
    price_min: 25000,
    price_max: 80000,
    price_unit: 'one_time',
    price_range: '£25,000-80,000',
    equipment: ['Custom built to spec'],
    features: ['Vintage food truck restoration', 'Head-turning builds', 'Bespoke designs'],
    best_for_business: ['mobile'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['2000-5000', '5000+'],
    cuisine_strength: ['all'],
    website: 'https://foodtruckmasters.com',
    description: 'Vintage food truck restoration specialists. Head-turning builds.',
    active: true,
    verified: false,
  },

  // ─── MARKETPLACES ─────────────────────────────────────────────────────
  {
    id: 'oya',
    name: 'Oya',
    type: 'marketplace',
    cities: ['London', 'Manchester', 'Birmingham', 'Leeds', 'Bristol', 'Edinburgh', 'Glasgow', 'Cardiff', 'Liverpool', 'Sheffield', 'Newcastle', 'Nottingham', 'Derby', 'Leicester'],
    price_min: 400,
    price_max: 8000,
    price_unit: 'month',
    price_range: 'Various',
    equipment: ['Varies by listing'],
    features: ['Large selection', 'Direct contact', 'Compare options', 'Reviews available'],
    best_for_business: ['all'],
    best_for_scale: ['all'],
    best_for_budget: ['all'],
    cuisine_strength: ['all'],
    website: 'https://oya.co.uk',
    description: 'UK marketplace for commercial kitchen rentals. Browse and compare options across the country.',
    active: true,
    verified: false,
  },
  {
    id: 'kitchen-space-rentals',
    name: 'Kitchen Space Rentals',
    type: 'marketplace',
    cities: ['London', 'Manchester', 'Birmingham', 'Leeds', 'Bristol', 'Edinburgh', 'Glasgow', 'Liverpool', 'Sheffield', 'Newcastle', 'Nottingham', 'Cardiff', 'Belfast', 'Brighton'],
    price_min: 15,
    price_max: 200,
    price_unit: 'hour',
    price_range: 'Various',
    equipment: ['Varies by listing'],
    features: ['1500+ kitchens', '34 cities', 'Instant booking', 'Verified listings'],
    best_for_business: ['starting', 'catering', 'popup', 'production'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['under-500', '500-1000', '1000-2000'],
    cuisine_strength: ['all'],
    website: 'https://kitchenspacerentals.com',
    description: 'Large aggregator of commercial kitchen spaces across the UK. Good for finding hourly or daily rentals.',
    active: true,
    verified: false,
  },
  {
    id: 'ncass-classifieds',
    name: 'NCASS Classifieds',
    type: 'marketplace',
    cities: ['Nationwide'],
    price_min: 5000,
    price_max: 45000,
    price_unit: 'one_time',
    price_range: 'Various',
    equipment: ['Varies'],
    features: ['Used equipment', 'Trailers', 'Vans', 'Industry trusted', 'Member listings'],
    best_for_business: ['mobile'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['500-1000', '1000-2000', '2000-5000'],
    cuisine_strength: ['all'],
    website: 'https://ncass.org.uk/classified-adverts',
    description: 'Industry classifieds for used catering equipment and vehicles. Good for budget-conscious mobile operators.',
    active: true,
    verified: false,
  },
  // dephna already listed as dark_kitchen - no duplicate needed for marketplace
  
  // ─── PRODUCTION KITCHENS ──────────────────────────────────────────────
  {
    id: 'food-works-sw',
    name: 'Food Works SW',
    type: 'production_kitchen',
    cities: ['Bristol', 'Exeter'],
    price_min: 1800,
    price_max: 4500,
    price_unit: 'month',
    price_range: '£1,800-4,500/mo',
    equipment: ['Commercial oven', 'Walk-in cold room', 'Prep tables', 'Storage shelving'],
    features: ['Food business incubator', 'Business support', 'Networking events'],
    best_for_business: ['production', 'starting'],
    best_for_scale: ['small', 'medium'],
    best_for_budget: ['1000-2000', '2000-5000'],
    cuisine_strength: ['Healthy / Salads', 'Desserts & Bakery', 'Coffee & Café'],
    website: 'https://foodworks-sw.co.uk',
    description: 'Food business incubator in the South West. Great for food startups needing production space plus business support.',
    active: true,
    verified: false,
  },
]

async function migrate() {
  console.log(`\n🚀 Starting migration of ${PROVIDERS.length} providers...\n`)

  // Batch upsert in chunks of 20
  const chunkSize = 20
  let totalInserted = 0
  let totalErrors = 0

  for (let i = 0; i < PROVIDERS.length; i += chunkSize) {
    const chunk = PROVIDERS.slice(i, i + chunkSize)
    const { data, error } = await supabase
      .from('providers')
      .upsert(chunk, { onConflict: 'id' })
      .select('id')

    if (error) {
      console.error(`❌ Error on chunk ${i / chunkSize + 1}:`, error.message)
      totalErrors += chunk.length
    } else {
      totalInserted += data?.length || chunk.length
      console.log(`✅ Chunk ${i / chunkSize + 1}: inserted/updated ${data?.length || chunk.length} providers`)
    }
  }

  console.log(`\n📊 Migration complete:`)
  console.log(`  ✅ Inserted/updated: ${totalInserted}`)
  console.log(`  ❌ Errors: ${totalErrors}`)
  console.log(`  📋 Total providers: ${PROVIDERS.length}`)

  // Verify
  const { data: verify, error: verifyError } = await supabase
    .from('providers')
    .select('id, name, type')
    .order('type')

  if (verifyError) {
    console.error('\n❌ Could not verify:', verifyError.message)
  } else {
    console.log(`\n✅ Verified ${verify?.length} providers in database:`)
    const byType = verify?.reduce((acc: Record<string, number>, p) => {
      acc[p.type] = (acc[p.type] || 0) + 1
      return acc
    }, {})
    for (const [type, count] of Object.entries(byType || {})) {
      console.log(`  ${type}: ${count}`)
    }
  }
}

migrate().catch(console.error)
